spring:
  application:
    name: spring-openai-demo

  ai:
#    ollama:
#      base-url: http://localhost:11434/
#      chat:
#        model: llama3.2:1b
#    openai:
#      api-key: ${OPENAI_API_KEY}
    google:
      genai:
        api-key: ${GEMINI_API_KEY}

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG


