spring:
  application:
    name: spring-openai-demo

  ai:
#    ollama:
#      base-url: http://localhost:11434/
#      chat:
#        model: llama3.2:1b
#    openai:
#      api-key: ${OPENAI_API_KEY}
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
#        chat:
#          model: gemini-2.5-flash
#          temperature: 0.3
#          max-output-tokens: 100
#          frequency-penalty: 0.7
#          presence-penalty: 0.7
#          stop-sequences:
#            - }
#          top-k: 50
#          top-p: 0.5

logging:
  level:
    org.springframework.ai.chat.client.advisor: DEBUG


